"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['src/gui.py']
DATA_FILES = []
OPTIONS = {'resources': 'src/default_colour.csv,src/title.gif,src/tree.gif,src/col.tree.gif'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
